server:
  assets-path: /app/assets

theme:
  background-color: 186 21 20
  contrast-multiplier: 1.2
  primary-color: 97 13 80

pages:
  - $include: home.yml
  - $include: videos.yml
  - $include: news.yml
  - $include: reddit.yml
